=== Adarshd19/Ignis/refs/ignis.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "ignis.schema.json",
    "title": "Ignis Rodent",
    "description": "Ignis rodent scene description language",
    "type": "object",
    "required": ["camera", "film"],
    "properties": {
        "technique": { "$ref": "#/definitions/Technique"},
        "camera": { "$ref": "#/definitions/Camera" },
        "film": { "$ref": "#/definitions/Film" },
        "materials": {
            "description": "List of materials",
            "type": "array",
            "items": { "$ref": "#/definitions/Material" },
            "uniqueItems": true
        },
        "meshes": {
            "description": "List of meshes",
            "type": "array",
            "items": { "$ref": "#/definitions/Mesh" },
            "uniqueItems": true
        },
        "entities": {
            "description": "List of entities",
            "type": "array",
            "items": {"$ref": "#/definitions/Entity" },
            "uniqueItems": true
        },
        "lights": {
            "description": "List of lights",
            "type": "array",
            "items": { "$ref": "#/definitions/Light" },
            "uniqueItems": true
        }
    },
    "definitions": {
        "Technique": {
            "description": "Technique properties",
            "type": "object",
            "required": ["type"],
            "properties": { 
                "type": { "type":"string"},
                "max_depth": { "type":"integer", "minimum":0 }
            },
            "additionalProperties": true
        },
        "Camera": {
            "description": "Camera properties",
            "type": "object",
            "required": [],
            "properties": { 
                "type": { "type":"string"},
                "fov": { "type":"number", "minimum":0 },
                "transform": { "$ref":"#/definitions/Transform" }
            },
            "additionalProperties": true
        },
        "Film": {
            "description": "Film/Image properties",
            "type": "object",
            "required": ["size"],
            "properties": { 
                "size": { "$ref":"#/definitions/Size" },
                "spp": { "type":"integer", "minimum":0 }
            },
            "additionalProperties": true
        },
        "Material": {
            "description": "Material properties",
            "type": "object",
            "required": ["type", "name"],
            "properties": { 
                "type": { "type":"string"},
                "name": { "type":"string"}
            },
            "additionalProperties": true
        },
        "Mesh": {
            "description": "Mesh properties",
            "type": "object",
            "required": ["type", "name", "filename"],
            "properties": { 
                "type": { "type":"string"},
                "name": { "type":"string"},
                "filename": { "type":"string"}
            },
            "additionalProperties": true
        },
        "Entity": {
            "description": "Material properties",
            "type": "object",
            "required": ["type", "name"],
            "properties": { 
                "type": { "type":"string"},
                "name": { "type":"string"},
                "transform": { "$ref":"#/definitions/Transform" },
                "material": { "type":"string" }
            },
            "additionalProperties": true
        },
        "Light": {
            "description": "Light properties",
            "type": "object",
            "required": ["type", "name"],
            "properties": { 
                "type": { "type":"string"},
                "name": { "type":"string"}
            },
            "additionalProperties": true
        },
        "Transform": {
            "description": "Transform properties",
            "type": "object",
            "required": [],
            "properties": { 
                "position": { "$ref":"#/definitions/Vector3" },
                "rotation": { "$ref":"#/definitions/Vector4" },
                "scale": { 
                    "oneOf":[
                        {"$ref":"#/definitions/Vector3"},
                        {"type":"number"}
                    ]
                },
                "matrix": { 
                    "oneOf":[
                        {"$ref":"#/definitions/Matrix3"},
                        {"$ref":"#/definitions/Matrix4"}
                    ]
                }
            }
        },
        "Size": {
            "type":"array",
            "minItems": 2,
            "maxItems": 2,
            "items": { "type": "number" }
        },
        "Vector3": {
            "type":"array",
            "minItems": 3,
            "maxItems": 3,
            "items": { "type": "number" }
        },
        "Vector4": {
            "type":"array",
            "minItems": 4,
            "maxItems": 4,
            "items": { "type": "number" }
        },
        "Matrix3": {
            "type":"array",
            "minItems": 9,
            "maxItems": 9,
            "items": { "type": "number" }
        },
        "Matrix4": {
            "type":"array",
            "minItems": 16,
            "maxItems": 16,
            "items": { "type": "number" }
        }
    }
}

=== Adarshd19/Ignis/refs/example.json
{
    "technique": {
        "type": "bdpt",
        "max_depth": 16
    },
    "camera": {
        "fov": 32,
        "transform": { "position": [0, 0, 0] }
    },
    "film": {
        "size": [1920, 1080],
        "spp": 4
    },
    "materials":[
        {"type":"diffuse", "name":"BunnyMaterial", "albedo":[1,0,0]},
        {"type":"principled", "name":"TeapotMaterial", "base":[0,1,1], "roughness":0.4}
    ],
    "meshes": [
        {"type":"obj", "name": "Teapot", "filename":"myteapot.obj"},
        {"type":"ply", "name": "Bunny", "filename":"bunny.ply"}
    ],
    "entities": [
        {"type":"mesh", "name": "Bunny", "material":"BunnyMaterial", "mesh":"Bunny", "transform":{ "position":[0,0,1] }},
        {"type":"mesh", "name": "Teapot", "material":"TeapotMaterial", "mesh":"Teapot", "transform":{ "position":[0,2,0] }},
        {"type":"plane", "name": "Light", "size": [1,1], "transform":{ "matrix":[1,0,0,0,0,1,0,1,0,0,-1,2,0,0,0,1] }}
    ],
    "lights": [
        {"type":"distant", "name": "Distant", "direction":[-1,0,0]},
        {"type":"area", "name": "AreaLight", "entity":"Light", "radiance":[1,1,1]}
    ]
}
